import { NextRequest, NextResponse } from "next/server";
export const runtime = "nodejs";
const ALLOWED_HOSTS=["ticket.interpark.com","tickets.interpark.com","nol.interpark.com","ticketlink.co.kr","www.ticketlink.co.kr","yes24.com","ticket.yes24.com","melonticket.com","ticket.melon.com","yeyak.seoul.go.kr"];
type TicketWindow={kind:"fan"|"general"|"accessible"|"application"|"unknown";label:string;startText:string;sourceText:string};
function allowed(url:string){try{const h=new URL(url).hostname.toLowerCase();return ALLOWED_HOSTS.some(x=>h===x||h.endsWith(`.${x}`));}catch{return false}}
function cleanHtml(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g,"\n").replace(/&nbsp;|&#160;/gi," ").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&amp;/gi,"&").replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/[ \t]+/g," ").replace(/\n{2,}/g,"\n")}
function classify(label:string):TicketWindow["kind"]{if(/팬클럽|선예매|presale/i.test(label))return"fan";if(/휠체어|장애/i.test(label))return"accessible";if(/일반예매|일반 예매|티켓오픈|티켓 오픈/i.test(label))return"general";if(/신청|접수|예약/i.test(label))return"application";return"unknown"}
function extract(text:string){const lines=text.split("\n").map(s=>s.trim()).filter(Boolean);const out:TicketWindow[]=[];const dateTime=/(20\d{2})\s*[년.\/-]\s*(\d{1,2})\s*[월.\/-]\s*(\d{1,2})\s*일?[^\n]{0,30}?(?:(오전|오후)\s*)?(\d{1,2})(?::(\d{2}))?\s*(?:AM|PM|시)?/i;for(let i=0;i<lines.length;i++){const line=lines[i];if(!/(예매|티켓|신청|접수|예약|오픈|휠체어)/.test(line))continue;const joined=[line,lines[i+1]||"",lines[i+2]||""].join(" ");const m=joined.match(dateTime);if(!m)continue;const label=(line.split(/[▶:：]/)[0]||line).slice(0,60);const sourceText=joined.slice(0,220);if(out.some(v=>v.sourceText===sourceText))continue;out.push({kind:classify(label),label,startText:m[0].trim(),sourceText})}return out.slice(0,12)}
export async function GET(req:NextRequest){const url=req.nextUrl.searchParams.get("url")||"";if(!url||!allowed(url))return NextResponse.json({ok:false,windows:[],reason:"지원 예매처가 아니거나 URL이 없습니다."},{status:400});try{const res=await fetch(url,{headers:{"user-agent":"Mozilla/5.0 SHOWDAY/1.0","accept-language":"ko-KR,ko;q=0.9"},next:{revalidate:1800},redirect:"follow"});if(!res.ok)return NextResponse.json({ok:false,windows:[],reason:`예매처 응답 ${res.status}`});const windows=extract(cleanHtml(await res.text()));return NextResponse.json({ok:true,windows,sourceUrl:url,verifiedAt:new Date().toISOString(),noticeFound:windows.length>0})}catch(e){return NextResponse.json({ok:false,windows:[],reason:e instanceof Error?e.message:"예매일정 확인 실패"})}}
