"use client";
import { useEffect, useState } from "react";

type Product = { id:string; title:string; description:string; image_url:string; product_url:string; price_label:string; sale_label:string; category:string; cta_label:string; is_active:boolean; is_featured:boolean; sort_order:number };
const empty = { title:"", description:"", image_url:"", product_url:"", price_label:"", sale_label:"", category:"추천상품", cta_label:"상품 보기", is_active:true, is_featured:false, sort_order:0 };

export default function AdminProductsPage(){
 const [items,setItems]=useState<Product[]>([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<string|null>(null); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState("");
 const load=async()=>{ const r=await fetch('/api/admin/products',{cache:'no-store'}); const d=await r.json(); if(r.ok)setItems(d.products||[]); else setMsg(d.error||'상품을 불러오지 못했습니다.'); };
 useEffect(()=>{load();},[]);
 const upload=async(file:File)=>{ const fd=new FormData(); fd.append('file',file); fd.append('folder','products'); setMsg('이미지 업로드 중...'); const r=await fetch('/api/admin/upload',{method:'POST',body:fd}); const d=await r.json(); if(r.ok){setForm(v=>({...v,image_url:d.url}));setMsg('이미지가 등록되었습니다.');} else setMsg(d.error||'업로드 실패'); };
 const save=async()=>{ if(!form.title.trim()||!form.product_url.trim()){setMsg('상품명과 상품 링크를 입력해주세요.');return;} setSaving(true); setMsg(''); const url=editing?`/api/admin/products/${editing}`:'/api/admin/products'; const r=await fetch(url,{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); const d=await r.json(); setSaving(false); if(!r.ok){setMsg(d.error||'저장 실패');return;} setForm(empty);setEditing(null);setMsg('저장되었습니다.');load(); };
 const edit=(p:Product)=>{setEditing(p.id);setForm({title:p.title,description:p.description||'',image_url:p.image_url||'',product_url:p.product_url,price_label:p.price_label||'',sale_label:p.sale_label||'',category:p.category||'추천상품',cta_label:p.cta_label||'상품 보기',is_active:p.is_active,is_featured:p.is_featured,sort_order:p.sort_order||0});window.scrollTo({top:0,behavior:'smooth'});};
 const patch=async(p:Product, changes:Partial<Product>)=>{await fetch(`/api/admin/products/${p.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(changes)});load();};
 const remove=async(p:Product)=>{if(!confirm(`“${p.title}” 상품을 삭제할까요?`))return;await fetch(`/api/admin/products/${p.id}`,{method:'DELETE'});load();};
 const input='mt-1 w-full rounded-xl border border-[#e7dcc9] bg-white px-3.5 py-3 text-sm outline-none focus:border-[#b3742f]';
 return <div>
  <div className="rounded-2xl bg-gradient-to-br from-[#241a10] to-[#3d2a17] p-7 text-white"><p className="text-[11px] font-bold tracking-[.2em] text-[#e8a353]">SHOWDAY SHOP</p><h1 className="mt-2 text-2xl font-black">판매상품 관리</h1><p className="mt-1 text-sm text-[#d8c3a4]">공연 가는 날 필요한 추천상품을 등록하고 고객 화면 노출을 관리합니다.</p></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_360px]">
   <div className="rounded-2xl border border-[#e7dcc9] bg-white p-6">
    <div className="flex items-center justify-between"><h2 className="font-black">{editing?'상품 수정':'새 상품 등록'}</h2>{editing&&<button className="text-xs font-bold text-[#8a7360] underline" onClick={()=>{setEditing(null);setForm(empty)}}>수정 취소</button>}</div>
    <div className="mt-5 grid gap-4 md:grid-cols-2">
     <label className="text-xs font-bold">상품명 *<input className={input} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="예: 공연 관람용 편안한 스니커즈"/></label>
     <label className="text-xs font-bold">카테고리<input className={input} value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="추천상품 / 신발 / 여행용품"/></label>
     <label className="text-xs font-bold md:col-span-2">상품 설명<textarea className={input} rows={2} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="고객에게 보일 짧은 설명"/></label>
     <label className="text-xs font-bold">판매가 표시<input className={input} value={form.price_label} onChange={e=>setForm({...form,price_label:e.target.value})} placeholder="29,900원"/></label>
     <label className="text-xs font-bold">혜택/할인 표시<input className={input} value={form.sale_label} onChange={e=>setForm({...form,sale_label:e.target.value})} placeholder="10% 할인 / 무료배송"/></label>
     <label className="text-xs font-bold md:col-span-2">상품 링크 *<input className={input} value={form.product_url} onChange={e=>setForm({...form,product_url:e.target.value})} placeholder="https://..."/></label>
     <label className="text-xs font-bold md:col-span-2">상품 이미지 URL<input className={input} value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="URL을 입력하거나 아래에서 업로드"/><input className="mt-2 block text-xs" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label>
     <label className="text-xs font-bold">버튼 문구<input className={input} value={form.cta_label} onChange={e=>setForm({...form,cta_label:e.target.value})}/></label>
     <label className="text-xs font-bold">노출 순서<input type="number" className={input} value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label>
    </div>
    <div className="mt-5 flex flex-wrap gap-5 text-sm font-bold"><label><input type="checkbox" className="mr-2" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>고객 화면에 노출</label><label><input type="checkbox" className="mr-2" checked={form.is_featured} onChange={e=>setForm({...form,is_featured:e.target.checked})}/>대표상품으로 노출</label></div>
    {msg&&<p className="mt-4 text-xs font-bold text-[#b3742f]">{msg}</p>}<button disabled={saving} onClick={save} className="mt-5 rounded-xl bg-[#241a10] px-6 py-3 text-sm font-black text-white disabled:opacity-40">{saving?'저장 중...':editing?'수정 저장':'상품 등록'}</button>
   </div>
   <div className="rounded-2xl border border-[#e7dcc9] bg-[#fffaf2] p-5"><p className="text-xs font-black text-[#b3742f]">CUSTOMER PREVIEW</p><div className="mt-3 overflow-hidden rounded-2xl bg-white shadow-sm">{form.image_url?<img src={form.image_url} alt="" className="aspect-[4/3] w-full object-cover"/>:<div className="grid aspect-[4/3] place-items-center bg-[#f0e6d6] text-xs text-[#8a7360]">상품 이미지를 등록해주세요</div>}<div className="p-4"><p className="text-[10px] font-black text-[#b3742f]">{form.category||'추천상품'} · SHOWDAY PICK</p><p className="mt-1 font-black">{form.title||'상품명이 여기에 표시됩니다'}</p>{form.description&&<p className="mt-1 text-xs text-[#8a7360]">{form.description}</p>}<div className="mt-2 flex gap-2 text-xs font-black">{form.price_label&&<span>{form.price_label}</span>}{form.sale_label&&<span className="text-[#b3742f]">{form.sale_label}</span>}</div></div></div></div>
  </div>
  <div className="mt-6 rounded-2xl border border-[#e7dcc9] bg-white p-6"><h2 className="font-black">등록 상품 <span className="text-[#b3742f]">{items.length}</span></h2><div className="mt-4 space-y-3">{items.length===0?<p className="text-sm text-[#8a7360]">등록된 상품이 없습니다.</p>:items.map(p=><div key={p.id} className="flex flex-col gap-3 rounded-xl border border-[#eee3d3] p-3 sm:flex-row sm:items-center"><div className="h-20 w-20 shrink-0 overflow-hidden rounded-xl bg-[#f7f0e4]">{p.image_url&&<img src={p.image_url} alt="" className="h-full w-full object-cover"/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><b>{p.title}</b>{p.is_featured&&<span className="rounded-full bg-[#241a10] px-2 py-0.5 text-[10px] font-black text-white">대표</span>}<span className={`rounded-full px-2 py-0.5 text-[10px] font-black ${p.is_active?'bg-green-50 text-green-700':'bg-gray-100 text-gray-500'}`}>{p.is_active?'노출중':'숨김'}</span></div><p className="mt-1 text-xs text-[#8a7360]">{p.category} · {p.price_label||'가격 미표시'} · 순서 {p.sort_order}</p></div><div className="flex gap-2"><button onClick={()=>patch(p,{is_active:!p.is_active})} className="rounded-lg border px-3 py-2 text-xs font-bold">{p.is_active?'숨기기':'노출'}</button><button onClick={()=>edit(p)} className="rounded-lg border px-3 py-2 text-xs font-bold">수정</button><button onClick={()=>remove(p)} className="rounded-lg border border-red-100 px-3 py-2 text-xs font-bold text-red-600">삭제</button></div></div>)}</div></div>
 </div>
}
